### ISSUE TITLE
Browser

### ISSUE THREAD

**Issue by jpbourgeon** [junaway/flexid#1]
Hi,

Your project seems very promising !

How does your library behave in a browser context ?

My current project will need Universally-unique Lexicographic Identifiers AND to work equally on the client side (ideally in a service worker) or the server. I settled to ULIDx so far but you library may be a good challenger :-)

**Comment by junaway** [comment]
Hi @jpbourgeon,

Check out v0.8.3 where there is an example on how to use it with webpack on the browser. Just so you know, I only added the example, the module was already browser-compatible (modulo the use of polyfills).

Let me know if that works for you.
